#!/usr/bin/env sh

RESULT=0

check() {
	output=$($1 2>&1)
	result=$?
	if [ "$result" -eq "0" ]; then
		echo "✅ PASS: $1"
	else
		echo "❌ FAIL: $1"
		echo "$output"
		RESULT=1
	fi
}

CHANGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR)
if [ -z "$CHANGED_FILES" ]; then
	echo "No relevant files added/changed, no checks run"
	exit 0
fi

POETRY_CHANGED_FILES=$(echo "$CHANGED_FILES" | grep --extended-regexp "^(pyproject\.toml|poetry\.lock)$")
if [ -n "$POETRY_CHANGED_FILES" ]; then
    check "poetry check"
	check "poetry lock --check" # deprecated, remove when upgrading to poetry v2
	check "poetry install"
fi

PY_CHANGED_FILES=$(echo "$CHANGED_FILES" | grep "\.py$")
if [ -n "$PY_CHANGED_FILES" ]; then
	PY_CHANGED_FILES_ARGS=$(echo "$PY_CHANGED_FILES" | tr '\n' ' ')
	check "poetry run mypy --explicit-package-bases $PY_CHANGED_FILES_ARGS"
	check "poetry run ruff check $PY_CHANGED_FILES_ARGS"
fi

exit $RESULT
