name: Mark as Done
permissions: {}

on:
  push:
    tags:
      - v*

jobs:
  mark-as-done:
    runs-on: ubuntu-latest
    steps:
      - name: Move closed issues and merged PRs to the "✅ Done" column
        uses: grafana/auto-mate@fec4390aee45a9b143209fc465315b82a7032e00 # v1
        with:
          token: ${{ secrets.AUTO_MATE_TOKEN }}
          projectNo: 346
